import numpy as np
arr=np.array([1,4,9,16])
print("Original Array:\t",arr)
print("\nMathematical functions")
print("Square Root:\t",np.sqrt(arr))
print("Sum:\t\t",np.sum(arr))
print("Mean:\t\t",np.mean(arr))
print("Maximum:\t",np.max(arr))
print("Minimum:\t",np.min(arr))
print("\nTrigonometric functions")
print("Sine:\t\t",np.sin(arr))
print("Cosine:\t\t",np.cos(arr))
print("\nExponential function (e^x)")
print("Exponential:\t",np.exp(arr))