import numpy as np
arr=np.array([10,20,30,40,50,60,70,80,90])
print("Original Array:\t\t\t",arr)
print("\nBasic Indexing")
print("First element:\t\t\t",arr[0])
print("Fourth element:\t\t\t",arr[3])
print("Last element:\t\t\t",arr[-1])
print("\nAdvanced Indexing")
indices=np.array([0,2,4,6])
print("Elements at indices:\t\t",arr[indices])
print("Elements greater than 50:\t",arr[arr>50])
print("Even elements:\t\t\t",arr[arr%2==0])
print("Elements at indices [1,3,3,7]:\t",arr[[1,3,3,7]])
print("\nBasic Slicing")
print("arr[2:6]:\t\t\t",arr[2:6])
print("arr[5:]:\t\t\t",arr[5:])
print("arr[:4]:\t\t\t",arr[:4])
print("arr[::2]:\t\t\t",arr[::2])
print("arr[::-1]:\t\t\t",arr[::-1])
print("\nSlice Modification")
arr_copy=arr.copy()
arr_copy[2:5]=[300,400,500]
print("After Modifying Slice [2:5]\t",arr_copy)